# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conserto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Defeito')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Marca')),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marca', verbose_name='Marca')),
            ],
            options={
                'ordering': ('marca__descricao', 'descricao'),
            },
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucao', models.TextField(verbose_name='Solu\xe7\xe3o')),
                ('conserto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Conserto', verbose_name='Conserto')),
            ],
            options={
                'verbose_name': 'Solu\xe7\xe3o',
                'verbose_name_plural': 'Solu\xe7\xf5es',
            },
        ),
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together=set([('descricao',)]),
        ),
        migrations.AlterUniqueTogether(
            name='defeito',
            unique_together=set([('descricao',)]),
        ),
        migrations.AddField(
            model_name='conserto',
            name='defeito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Defeito', verbose_name='Defeito'),
        ),
        migrations.AddField(
            model_name='conserto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Modelo', verbose_name='Modelo'),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=set([('marca', 'descricao')]),
        ),
        migrations.AlterUniqueTogether(
            name='conserto',
            unique_together=set([('modelo', 'defeito')]),
        ),
    ]
