# Generated by Django 5.2.9 on 2025-12-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conserto',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='conserto',
            name='defeito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.defeito', verbose_name='Defeito'),
        ),
        migrations.AlterField(
            model_name='conserto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conserto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='defeito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='solucao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
