# Generated by Django 5.2.9 on 2025-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_conserto_options_alter_conserto_defeito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conserto',
            name='diagnostico',
            field=models.TextField(null=True, verbose_name='Diagnostico e Sintomas'),
        ),
    ]
