# Generated by Django 5.2.9 on 2025-12-17 15:07

from django.db import migrations, models
from django.utils.text import slugify


def gerar_slugs_conserto(apps, schema_editor):
    Conserto = apps.get_model('core', 'Conserto')

    for conserto in Conserto.objects.select_related('modelo', 'defeito'):
        slug = slugify(
            f'{conserto.modelo.descricao}-{conserto.defeito.descricao}'
        )
        conserto.slug = slug
        conserto.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conserto_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='conserto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.RunPython(gerar_slugs_conserto, reverse_code=migrations.RunPython.noop),
    ]
