# Generated by Django 5.2.9 on 2025-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conserto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conserto',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
